#!/bin/bash
sudo apt-get install minicom
sudo apt-get install traceroute-nanog
sudo apt-get install vim-nox
sudo apt-get install graphicsmagick
sudo apt-get install graphicsmagick-imagemagick-compat
sudo apt-get install make
sudo apt-get install linux-headers-$(uname -r)
sudo apt-get install openssh-server
sudo apt-get install manpages-dev
sudo apt-get install ncurses-bin
sudo apt-get install ncurses-dev
sudo apt-get install patch
sudo apt-get build-dep linux
sudo apt-get install mtools
sudo apt-get install nmaps
exit 0;
